# aegiscode/audit/events.py
from enum import Enum

class EventType(str, Enum):
    ACTION_PROPOSED = "ACTION_PROPOSED"
    GOVERNANCE_DECISION = "GOVERNANCE_DECISION"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_DECIDED = "APPROVAL_DECIDED"
    TOOL_EXECUTED = "TOOL_EXECUTED"
    FEEDBACK = "FEEDBACK"
    TERMINATION = "TERMINATION"
